version: '2'
services:
    epics-archiver:
        container_name: epics-archiver
        image: lnlscon/epics-archiver-single:latest
        hostname: localhost
        network_mode: "host"
        dns:
            - 10.0.0.71
            - 10.0.0.72
        ports:
            - 11995:11995
            - 11996:11996
            - 11997:11997
            - 11998:11998
        depends_on:
            - epics-archiver-mysql-db
        volumes:
            - epics-archiver-sts-volume:/opt/epics-archiver-appliances/storage/sts
            - epics-archiver-mts-volume:/opt/epics-archiver-appliances/storage/mts
            - epics-archiver-lts-volume:/opt/epics-archiver-appliances/storage/lts
            - ./configuration:/opt/epics-archiver-appliances/configuration
        env_file:
            - ./configuration/lnls-epics-archiver.env

    epics-archiver-mysql-db:
        container_name: epics-archiver-mysql-db
        image: lnlscon/epics-archiver-mysql-db:latest
        hostname: epics-archiver-mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=controle
            - MYSQL_USER=lnls_user
            - MYSQL_PASSWORD=controle
            - MYSQL_DATABASE=lnls_archiver_db
        network_mode: "host"
        dns:
            - 10.0.0.71
            - 10.0.0.72
        volumes:
            - epics-archiver-mysql-db-volume:/var/lib/mysql

volumes:
    epics-archiver-sts-volume:
        driver: local
    epics-archiver-mts-volume:
        driver: local
    epics-archiver-lts-volume:
        driver: local
    epics-archiver-mysql-db-volume:
        driver: local
